name: setup-azurestorage-action
description: Set up an Azure Storage account for testing
inputs:
  connection-string-name:
    description: The name of the environment variable to fill with the Azure Storage account connection string
    required: true
  tag:
    description: The name of the component Azure Storage is being used for. The storage account in Azure is tagged with this value.
    required: true
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js